import { Router, type IRouter } from "express";
import healthRouter from "./health";
import postsRouter from "./posts";
import categoriesRouter from "./categories";
import reactionsRouter from "./reactions";
import commentsRouter from "./comments";
import gistsRouter from "./gists";
import usersRouter from "./users";
import visitsRouter from "./visits";
import adminRouter from "./admin";
import voteCardsRouter from "./vote_cards";
import trendingRouter from "./trending";
import leaderboardRouter from "./leaderboard";
import eventsRouter from "./events";
import transactionsRouter from "./transactions";
import adsRouter from "./ads";
import contestsRouter from "./contests";
import subscriptionsRouter from "./subscriptions";
import marketplaceRouter from "./marketplace";
import connectionsRouter from "./connections";
import servicesRouter from "./services";
import recruitmentRouter from "./recruitment";
import spillRouter from "./spill";
import pushRouter from "./push";
import ogRouter from "./og";

const router: IRouter = Router();

router.use(healthRouter);
router.use(postsRouter);
router.use(categoriesRouter);
router.use(reactionsRouter);
router.use(commentsRouter);
router.use(gistsRouter);
router.use(usersRouter);
router.use(visitsRouter);
router.use(adminRouter);
router.use(voteCardsRouter);
router.use(trendingRouter);
router.use(leaderboardRouter);
router.use(eventsRouter);
router.use(transactionsRouter);
router.use(adsRouter);
router.use(contestsRouter);
router.use(subscriptionsRouter);
router.use(marketplaceRouter);
router.use(connectionsRouter);
router.use(servicesRouter);
router.use(recruitmentRouter);
router.use(spillRouter);
router.use(pushRouter);
router.use(ogRouter);

export default router;
